### Read example CME Datamine Top-of-Book records for CLK20 on 2020-03-12. 

There are over 85 million rows of bid/ask quote information that occured during this day.  They have been stored in 86 csv files, each having 1 million rows except `df_clk20_tob_85.csv`, which has the remaining rows.

In [7]:
import pandas as pd

In [3]:
df_tob_03 = pd.read_csv('../sports_betting_apis/temp_folder/c')
df_tob_03.tail()

,Trade Date,Trade Time,Trade Sequence Number,Session Indicator,Ticker Symbol,FOI Indicator,Delivery Date,Trade Quantity,Strike Price,Strike Price Decimal Locator,...,Market Quote,Close/Open Type,Valid Open Exception,Post Close,Cancel Code Type,Insert Code Type,Fast/Late Indicator,Cabinet Indicator,Book Indicator,Entry Date
999995,20200312,85447,28048161,E,CL,F,2004,9,,0,...,M,,,,,,,,,200312
999996,20200312,85447,28048162,E,CL,F,2004,17,,0,...,M,,,,,,,,,200312
999997,20200312,85447,28048162,E,CL,F,2004,9,,0,...,M,,,,,,,,,200312
999998,20200312,85447,28048166,E,CL,F,2004,8,,0,...,M,,,,,,,,,200312
999999,20200312,85447,28048166,E,CL,F,2004,17,,0,...,M,,,,,,,,,200312

In [4]:
df_tob_01 = pd.read_csv('../sports_betting_apis/temp_folder/df_clk20_tob_01.csv')
df_tob_01.tail()

,Trade Date,Trade Time,Trade Sequence Number,Session Indicator,Ticker Symbol,FOI Indicator,Delivery Date,Trade Quantity,Strike Price,Strike Price Decimal Locator,...,Market Quote,Close/Open Type,Valid Open Exception,Post Close,Cancel Code Type,Insert Code Type,Fast/Late Indicator,Cabinet Indicator,Book Indicator,Entry Date
999995,20200312,33106,26264713,E,CL,F,2004,9,,0,...,M,,,,,,,,,200312
999996,20200312,33106,26264713,E,CL,F,2004,12,,0,...,M,,,,,,,,,200312
999997,20200312,33106,26264714,E,CL,F,2004,11,,0,...,M,,,,,,,,,200312
999998,20200312,33106,26264714,E,CL,F,2004,9,,0,...,M,,,,,,,,,200312
999999,20200312,33106,26264716,E,CL,F,2004,6,,0,...,M,,,,,,,,,200312

In [6]:
23*60*60*1000/85000000

0.9741176470588235